import type { Metadata } from "next";
import { Poppins,Inter} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600","700", "800", "900"],
  style: ["normal"], // Например, добавляем несколько весов
});
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600","700", "800", "900"],
  style: ["normal"], // Например, добавляем несколько весов
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
